spring:
  # thymeleaf配置
  thymeleaf:
    # 关闭缓存
    cache: false
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill
    # 数据库账号与密码
    username: root
    password: 2054865827
    hikari:
      # 连接池名
      pool-name: DateHikariCP
      # 最小空闲输出
      minimum-idle: 5
      # 空闲连接存活最大时间,默认为600000(10分钟)
      idle-timeout: 600000
      # 最大连接数,默认为10
      maximum-pool-size: 10
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 连接最大存活时间, 0代表永久存活, 默认1800000(30分钟)
      max-lifetime: 1800000
      # 连接超时时间，默认为30000(30秒)
      connection-timeout: 30000
      # 类似于心跳机制,测试连接是否可用的查询语句（若通过该查询语句能够查询成功，则说明连接没问题）
      connection-test-query: SELECT 1

  # redis配置
  data:
    redis:
      #（云）服务器地址
      host: 118.178.229.132
      #端口
      port: 6379
      #数据库默认为第0号库
      database: 0
      #超时时间
      timeout: 10000ms
      #lettuce连接池的配置
      lettuce:
        pool:
          #最大连接数，默认为8
          max-active: 8
          #最大连接阻塞等待时间，默认-1
          max-wait: 10000ms
          #最大空闲连接，默认为8
          max-idle: 200
          #最小空闲连接，默认为0
          min-idle: 5

  web:
    #静态资源处理
    resources:
      #启用默认静态资源管理，默认启用
      add-mappings: true
      cache:
        cachecontrol:
          #缓存响应时间，单位是秒
          max-age: 3600
      chain:
        #资源链自动缓存，默认启动
        cache: true
        #启动资源链，默认禁用
        enabled: true
        #启用压缩资源(gzip,brotli等)，默认禁用
        compressed: true
      #静态资源目录
      static-locations: classpath:/static/

  #RabbitMQ
  rabbitmq:
    #服务器
    host: 192.168.136.129
    #用户名
    username: xsj
    #密码
    password: 123456
    #虚拟主机
    virtual-host: /
    #端口
    port: 5672
    listener:
      simple:
        #消费者的最小数量
        concurrency: 10
        #消费者最大数量
        max-concurrency: 10
        #限制消费者每次只能处理一条消息，处理完再继续下一条消息
        prefetch: 1
        #启动时是否默认启动容器，默认为true
        auto-startup: true
        #发送的消息如果被拒绝就重新进入队列
        default-requeue-rejected: true
    template:
      #发送的消息如果发送失败就重试
      retry:
        #发布重试，默认为false
        enabled: true
        #重试时间，默认为1000ms
        initial-interval: 1000ms
        #重试最大次数，默认为3次
        max-attempts: 3
        #重试最大间隔时间，默认为10000ms
        max-interval: 10000ms
        #重试的间隔倍数，如为2时，第一次等10s，第二次等20s，第三次等40s
        multiplier: 1



# mybatis-plus配置
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # 配置mybatis数据返回类型的别名(默认别名是类名)
  type-aliases-package: com.meeting_smile.seckilldemo.pojo

# mybatis SQL打印(方法接口所在的包，不是Mapper.xml所在的包)
logging:
  level:
    com.meeting_smile.seckilldemo.mapper: debug
